In [1]:
import numpy as np

In [2]:
vec_1 = np.array([1, 5, 8, 13, 4])

In [4]:
#インデックス４を抽出
vec_1[4]

np.int64(4)

In [5]:
#インデックス１～３を抽出
vec_1[1:4]

array([ 5,  8, 13])

In [6]:
#論理値ベクトル
vec_bool = np.array([True, False, True, True, False])

In [7]:
vec_bool

array([ True, False,  True,  True, False])

In [8]:
#論理値ベクトルがTrueのところ（インデックス０，２，３）を抽出
vec_1[vec_bool]

array([ 1,  8, 13])

In [11]:
#5以上の要素を抽出
vec_1[vec_1 >= 5]

array([ 5,  8, 13])

In [12]:
vec_1 >= 5

array([False,  True,  True,  True, False])