規則的なベクトルの作成

In [1]:
import numpy as np

arange

In [2]:
#１から１０までの等差１の等差ベクトル
#np.arange(x, y, z): xからyまでの等差zの等差ベクトル
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

linspace

In [5]:
#１から１０までの長さ４の等差ベクトル
#np.linspace(x, y, z): xからyまでの長さ４の等差ベクトル
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

repeat

In [6]:
#１を３回繰り返す
#np.repeat(vec, n): vecの要素をn回繰り返す
np.repeat(1, 3)

array([1, 1, 1])

In [7]:
#1を３回、２を３回繰り返す
np.repeat(np.array([1, 2]), 3)

array([1, 1, 1, 2, 2, 2])

tile

In [9]:
#１を３回繰り返す
#np.tile(vec, n): vecをn回繰り返す
np.tile(1, 3)

array([1, 1, 1])

In [11]:
#(1, 2)を３回繰り返す
np.tile(np.array([1, 2]), 3)

array([1, 2, 1, 2, 1, 2])