論理値ベクトルの計算

In [1]:
import numpy as np

In [2]:
#キャベツのサイズを示したベクトル定義
vec_size = np.array([7, 13, 5, 25, 38, 57, 18, 9, 32, 28])

In [3]:
#サイズ１０以上か？
vec_bool_1 = vec_size >= 10
#サイズ３０以下か？
vec_bool_2 = vec_size <= 30

In [4]:
vec_bool_1

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True])

In [5]:
vec_bool_2

array([ True,  True,  True,  True, False, False,  True,  True, False,
        True])

In [7]:
#AND
vec_bool_1 & vec_bool_2

array([False,  True, False,  True, False, False,  True, False, False,
        True])

In [8]:
#OR
vec_bool_1 | vec_bool_2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
#XOR
vec_bool_1 ^ vec_bool_2

array([ True, False,  True, False,  True,  True, False,  True,  True,
       False])

In [10]:
#NOT
~vec_bool_1

array([ True, False,  True, False, False, False, False,  True, False,
       False])

In [11]:
#any 
#１つ以上TRUE→TRUE　全部FALSE→FALSE
np.any(vec_bool_1)

np.True_

In [12]:
#all 
#全部TRUE→TRUE　１つ以上FALSE→FALSE
np.all(vec_bool_1)

np.False_