論理値ベクトルの作成

In [1]:
import numpy as np

In [3]:
x = np.arange(1, 11, 1)
y = np.array([1, 7, 4, 6, 2])
y_2 = np.tile(y, 2)

In [4]:
#xとy_2は等しいか？
x == y_2

array([ True, False, False, False, False, False,  True, False, False,
       False])

In [5]:
#xとy_2は等しくないか？
x != y_2

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [6]:
#xはy_2以上か？
x >= y_2

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True])

In [8]:
#xはyに含まれるか？
np.isin(x, y)

array([ True,  True, False,  True, False,  True,  True, False, False,
       False])