In [2]:
#パッケージ
import numpy as np

In [3]:
#ベクトル
vec_1 = np.array([1, 5, 8, 13, 4])
vec_2 = np.array([2, 3, 5, 10, 98])

In [5]:
vec_1

array([ 1,  5,  8, 13,  4])

In [6]:
vec_2

array([ 2,  3,  5, 10, 98])

In [7]:
#足し算
vec_1 + vec_2

array([  3,   8,  13,  23, 102])

In [8]:
#引き算
vec_1 - vec_2

array([ -1,   2,   3,   3, -94])

In [9]:
#掛け算
vec_1 * vec_2

array([  2,  15,  40, 130, 392])

In [10]:
#割り算
vec_1 / vec_2

array([0.5       , 1.66666667, 1.6       , 1.3       , 0.04081633])